---
- name: Add Sensu repo key
  shell: "wget -q http://repos.sensuapp.org/apt/pubkey.gpg -O- | sudo apt-key add -"

- name: Add the Sensu repo
  apt_repository: repo='deb http://repos.sensuapp.org/apt sensu main' state=present

- name: Install Sensu
  apt: name=sensu update_cache=yes
