#!/bin/sh

# this script is to be driven by OpenVPN service and run after the connection established

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Make sure only root can run our script
if [ "$(id -u)" != "0" ]; then
echo "This script must be run as root" 1>&2
exit 1
fi

# Load configuration
. /etc/route53/config

# Export access key ID and secret for cli53
export AWS_ACCESS_KEY_ID
export AWS_SECRET_ACCESS_KEY

# Use command line scripts to get instance ID and public hostname
INSTANCE_ID=$HOST_NAME
VPN_IP=$4

# Create a new CNAME record on Route 53, replacing the old entry if nessesary
LANADD=".vpn"
cli53 rrcreate "$ZONE" "$INSTANCE_ID$LANADD" A "$VPN_IP" --replace --ttl "$TTL"
