#!/bin/sh

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Make sure only root can run our script
if [ "$(id -u)" != "0" ]; then
echo "This script must be run as root" 1>&2
exit 1
fi

# Load configuration
. /etc/route53/config

# Export access key ID and secret for cli53
export AWS_ACCESS_KEY_ID
export AWS_SECRET_ACCESS_KEY

# Use command line scripts to get instance ID and public hostname
#INSTANCE_ID=$(ec2metadata | grep 'instance-id:' | cut -d ' ' -f 2)
INSTANCE_ID=$HOST_NAME
# PUBLIC_HOSTNAME=$(ec2metadata | grep 'public-hostname:' | cut -d ' ' -f 2)
PUBLIC_IPv4=$(ec2metadata | grep 'public-ipv4' | cut -d ' ' -f 2)
LAN_IPv4=$(ec2metadata | grep 'local-ipv4' | cut -d ' ' -f 2)

# Create a new CNAME record on Route 53, replacing the old entry if nessesary
# cli53 rrcreate "$ZONE" "$INSTANCE_ID" CNAME "$PUBLIC_HOSTNAME" --replace --ttl "$TTL"
LANADD=".internal"
cli53 rrcreate "$ZONE" "$INSTANCE_ID" A "$PUBLIC_IPv4" --replace --ttl "$TTL"
cli53 rrcreate "$ZONE" "$INSTANCE_ID$LANADD" A "$LAN_IPv4" --replace --ttl "$TTL"
